name: Docker Image Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the jinaga-postgres-fact-keystore image
      run: docker build ./jinaga-postgres-fact-keystore --file ./jinaga-postgres-fact-keystore/Dockerfile --tag jinaga/jinaga-postgres-fact-keystore:$(date +%s)
    - name: Build the jinaga-replicator image
      run: docker build ./jinaga-replicator --file ./jinaga-replicator/Dockerfile --tag jinaga/jinaga-replicator:$(date +%s)
