name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          jinaga-postgres-fact-keystore:
            - 'jinaga-postgres-fact-keystore/**'
          jinaga-replicator:
            - 'jinaga-replicator/**'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      if: steps.changes.outputs.jinaga-postgres-fact-keystore == 'true' || steps.changes.outputs.jinaga-replicator == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata for jinaga-postgres-fact-keystore
      if: steps.changes.outputs.jinaga-postgres-fact-keystore == 'true'
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: jinaga/jinaga-postgres-fact-keystore

    - name: Publish the jinaga-postgres-fact-keystore image
      if: steps.changes.outputs.jinaga-postgres-fact-keystore == 'true'
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:jinaga-postgres-fact-keystore"
        file: "{{defaultContext}}:jinaga-postgres-fact-keystore/DOCKERFILE"
        push: true
        tags: |
          jinaga/jinaga-postgres-fact-keystore:$(date +%s)
          jinaga/jinaga-postgres-fact-keystore:latest

  
